// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function getDatabaseUrl() {
  const databaseUrl = process.env.DATABASE_URL;
  const prismaUrl = process.env.PRISMA_URL;
  if (prismaUrl && (!databaseUrl || databaseUrl.startsWith("prisma+"))) {
    return prismaUrl;
  }
  return databaseUrl || prismaUrl || "";
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.js",
  },
  datasource: {
    url: "postgresql://neondb_owner:npg_qPtzu9VAbJ4Q@ep-odd-dew-aqneacy5.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require",
  },
});
